feat: File inputs not able to be a single file
uw-ssec/offshore-geodesy pull request #190
Opened 2023-11-24 11:10 UTC by madhavmk

* gather_files() returns dictionary of type Dict[str, List[str]]. all_files_dict dictionary values are now list of strings, even in case of single file value.
* load_sound_speed() and load_deletions() modified to concatenate dataframes if multiple file input provided.
* Unittests modified to support above changes.
* tests/data/2022/NCL1/ctd/CTD_NCL_Ch_Mi, tests/data/2022/NCL2/ctd/CTD_NCL_Ch_Mi, tests/data/2022/NCL1/deletns.dat, tests/data/2022/NCL2/deletns.dat test files modified/added.
* Fixes Issue #184

2023-11-24 11:35 UTC, madhavmk commented
Hello @johnbdesanto,
The config.yaml now accepts both single-file and multi-file values for sound_speed, travel_times, gps_solution, and deletions:
e.g.
```
  input_files:
    sound_speed:
      path: ./tests/data/2022/**/ctd/CTD_NCL_Ch_Mi
    travel_times:
      path: ./tests/data/2022/NCL1/**/WG_*/pxp_tt
    gps_solution:
      path: ./tests/data/2022/NCL1/208/posfilter/POS_FREED_TRANS_TWTT
    deletions:
      path: ./tests/data/2022/NCL1/deletns.dat
```
I have performed tests with the sample test data. It would be really helpful if you could verify that this is also working with actual data and config on your system. 
Thank you !

2023-11-27 18:25 UTC, lsetiawan requested changes
Thanks for these changes @madhavmk  😄 However, the new, duplicated test data created are not in the right structure. 
- `NCL1` is the site ID that the data is captured from, therefor having `NCL2` doesn't make sense and can be a source of confusion.
- There are docstrings in code that doesn't make sense, please see my inline comment above.

If you can, please don't modify the test data directly, but rather you can do so on the fly.

2023-11-27 20:42 UTC, madhavmk commented on src/gnatss/loaders.py
> +        """
You are right. My bad. I must have rebased and forgot to remove this extra docstring.

2023-11-27 21:26 UTC, lsetiawan approved these changes

2023-11-27 21:27 UTC, merged