Add method for computing harmonic mean
uw-ssec/offshore-geodesy pull request #66
Opened 2023-04-06 19:55 UTC by lsetiawan

## Overview

This PR resolves #65. It adds a method for computing harmonic mean from provided start and end depth of a transducer.

2023-04-06 23:10 UTC, carlosgjs approved these changes
Please see minor comments inline ...

2023-04-06 23:10 UTC, carlosgjs commented on src/seagap/harmonic_mean.py
> +):
type annotation for the return value?

2023-04-06 23:10 UTC, carlosgjs commented on src/seagap/harmonic_mean.py
> +    dd: np.ndarray,
might be usefult to document the dimensionality of these ndarrays

2023-04-06 23:10 UTC, carlosgjs commented on src/seagap/harmonic_mean.py
> +    start_depth: Union[int, float],
wouldn't `start_depth: float` be sufficient since that can also take an integer argument?

2023-04-06 23:10 UTC, carlosgjs commented on src/seagap/harmonic_mean.py
> +def sv_harmonic_mean(
same comments as above

2023-04-07 17:17 UTC, johnbdesanto requested changes
A few things:

1) I think we should change the name of the transponder_wait_time variable since it corresponds to the delay time of the surface platform. It is not associated with the seafloor transponders. "transducer_delay_time" or "surface_platform_delay_time" would be more to the point.

2) I'm not sure the validator from lines 171-176 is wholly neccessary. Thus far, we have only used surface platforms with delays of 0.0s or 0.1 s, but there is technically no reason why other platforms may have different delays. The current wave gliders have a delay of 0.13s, but I remove it earlier in the procesing chain so that I can simplify a 0.0s delay.

3) The harmonic_mean script seems like a 1-1 with the fortran script, so I assume it will work. However, I've noticed that scipy has a function called hmean, which is supposed to calculate a harmonic mean and may give us a similar estimate if we weight the sound velocity records by the depth differences. I am curious to see how it compares with the old fortran script.

2023-04-07 23:39 UTC, lsetiawan commented
> I think we should change the name of the transponder_wait_time variable since it corresponds to the delay time of the surface platform. It is not associated with the seafloor transponders. "transducer_delay_time" or "surface_platform_delay_time" would be more to the point.

In this PR that change is made. If you go to the `Files changed` tab above you can see the differences. The left side of the view is what the code used to be and the right side is what it's gonna be. This is essentially what's called a git diff. Anything colored red in the code means that they will be deleted and green is addition.

Also, you can review this guide on PR reviews where you are able to comment directly line by line https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request :)

2023-04-07 23:40 UTC, lsetiawan commented
> I'm not sure the validator from lines 171-176 is wholly neccessary. Thus far, we have only used surface platforms with delays of 0.0s or 0.1 s, but there is technically no reason why other platforms may have different delays. The current wave gliders have a delay of 0.13s, but I remove it earlier in the procesing chain so that I can simplify a 0.0s delay.

Thanks for this insight, when I initially set this up, I didn't have that knowledge, so I will remove the validator.

2023-04-07 23:42 UTC, lsetiawan commented
> The harmonic_mean script seems like a 1-1 with the fortran script, so I assume it will work. However, I've noticed that scipy has a function called hmean, which is supposed to calculate a harmonic mean and may give us a similar estimate if we weight the sound velocity records by the depth differences. I am curious to see how it compares with the old fortran script.

I am aware of scipy's hmean, but wasn't sure about what weight to use for it, and when I plug in the numbers directly into the scipy's function, it gave different result than the fortran, and the fortran code didn't exactly explain its formula 😬 so I just did a 1:1. Thanks for your insight for the weights. I'll try it out!

2023-04-08 00:24 UTC, lsetiawan commented
@johnbdesanto Trying out the scipy hmean function, I get the following results:

```
Transponder 1
start depth: -4.0
end depth: -1176.5866
fortran hm: 1481.551
scipy hm: 1481.56

Transponder 2
start depth: -4.0
end depth: -1146.5881
fortran hm: 1481.521
scipy hm: 1481.531

Transponder 3
start depth: -4.0
end depth: -1133.7305
fortran hm: 1481.509
scipy hm: 1481.518
```

They seem very close and just off by 0.01! Is this an okay difference? What are your thoughts? Thanks!

2023-04-08 02:08 UTC, johnbdesanto commented
These are essentially identical estimates given our uncertainty. I think
hmean is perfect for what we need. Glad to see they agreed so well!

On Fri, Apr 7, 2023 at 5:25 PM Don Setiawan ***@***.***>
wrote:

> @johnbdesanto
> <https://urldefense.com/v3/__https://github.com/johnbdesanto__;!!K-Hz7m0Vt54!lNOMcHkZRFzegzkZdDmQztXFdYTc84gKSBnHa71QdVCo2a2HzVMRdUKNoJWr0UAMaomtj3FXhPydBUXILgYDwHM$>
> Trying out the scipy hmean function, I get the following results:
>
> Transponder 1
> start depth: -4.0
> end depth: -1176.5866
> fortran hm: 1481.551
> scipy hm: 1481.56
>
> Transponder 2
> start depth: -4.0
> end depth: -1146.5881
> fortran hm: 1481.521
> scipy hm: 1481.531
>
> Transponder 3
> start depth: -4.0
> end depth: -1133.7305
> fortran hm: 1481.509
> scipy hm: 1481.518
>
> They seem very close and just off by 0.01! Is this an okay difference?
> What are your thoughts? Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/uw-ssec/offshore-geodesy/pull/66*issuecomment-1500740018__;Iw!!K-Hz7m0Vt54!lNOMcHkZRFzegzkZdDmQztXFdYTc84gKSBnHa71QdVCo2a2HzVMRdUKNoJWr0UAMaomtj3FXhPydBUXIurCsCQM$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AZKHBQ4ABYCWU6CRQZQJNUTXACV6BANCNFSM6AAAAAAWV2G5EE__;!!K-Hz7m0Vt54!lNOMcHkZRFzegzkZdDmQztXFdYTc84gKSBnHa71QdVCo2a2HzVMRdUKNoJWr0UAMaomtj3FXhPydBUXIk1MTJtk$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-10 17:07 UTC, lsetiawan commented
> These are essentially identical estimates given our uncertainty. I think
hmean is perfect for what we need. Glad to see they agreed so well!

Great! I will go ahead and convert the compute function to use the scipy's `hmean`! I really appreciate your inputs. 😄 Teamwork makes the dream work! 🥇

2023-04-10 18:52 UTC, lsetiawan commented
@johnbdesanto This is ready for another round of review from you. Thanks!

2023-04-10 19:03 UTC, johnbdesanto approved these changes

2023-04-10 19:07 UTC, lsetiawan commented
@carlosgjs Do you have any other suggestions, I've changed a couple of things since your last review. Thanks!

2023-04-10 19:23 UTC, carlosgjs commented
> @carlosgjs Do you have any other suggestions, I've changed a couple of things since your last review. Thanks!

LGTM!

2023-04-10 19:54 UTC, merged